### ISSUE TITLE
`error for getwalletinfo: RpcError { code: -32601, message: "Method not found", data: None }`

### ISSUE THREAD

**Issue by dpc** [bwt-dev/bwt#82]
I was going to try `bwt` and I hit the error from the subject. I suspect that I have to enable some wallet support in bitcoin-core, but what I don't understand is ... why? I thought that `bwt` is going to be handling the wallet management.

BTW. I might have missed it, but would be good to provide a list of required bitcoincore settings.

**Comment by shesek** [comment]
`bwt` uses the Bitcoin Core wallet internally and builds some additional indexes on top of it, so you are going to need wallet support enabled.

AFAIK the only requirements are this, and enabling the RPC server with `server=1` if you're using bitcoin-qt.
