### ISSUE TITLE
Connection via Bitcoin RPC fails in Bitcoin v23 rc2

### ISSUE THREAD

**Issue by craigraw** [bwt-dev/bwt#95]
As of [#23348](https://github.com/bitcoin/bitcoin/pull/23348) Bitcoin Core no longer returns "keypoololdest" for blank descriptor wallets, which causes BWT to fail with 
```
dev.bwt.libbwt.BwtException: JSON-RPC error: JSON decode error: missing field `keypoololdest` at line 1 column 336
```

See discussion at https://github.com/sparrowwallet/sparrow/issues/488

Given v23 is already in RC status, this appears to need urgent attention.

**Comment by craigraw** [comment]
It looks like the issue lies in the upstream rust-bitcoincore-rpc library, and would be fixed by merging https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/174.

Are there any workarounds?

**Comment by shesek** [comment]
> Are there any workarounds?

Yes, implemented in [`202203-createwallet`](https://github.com/bwt-dev/bwt/tree/202203-createwallet). I didn't test this properly yet though, was just on my way out. But you can give this a try :)

**Comment by craigraw** [comment]
Unfortunately I'm still getting the same error as above on startup with this branch.

Here's the (redacted) command I'm using:
```
target/release/bwt --network testnet --bitcoind-url http://127.0.0.1:18332 --bitcoind-auth bitcoin:password --bitcoind-wallet sparrow --electrum-addr 127.0.0.1:59754 --electrum-skip-merkle --descriptor "wpkh(tpub.../0/*)" --descriptor "wpkh(tpub.../1/*)" -vv -W
```

**Comment by craigraw** [comment]
Apologies, my mistake - looks like I didn't properly delete the descriptor wallet. After deleting it and restarting, I'm able to get BWT to startup fine, so it looks like this fix is working.

**Comment by shesek** [comment]
Alright, `202203-createwallet` was merged to master. Thanks for reporting this!

**Comment by ln3xp** [comment]
@shesek Running `./scripts/dev-env.sh` I get a similar error:

```
Error: JSON-RPC error: JSON decode error: missing field `keypoololdest` at line 1 column 332
```

 - BWT: latest `master`
 - Bitcoin Core: `v23.0.0`

**Comment by tadeubas** [comment]
@ln3xp I got the same error with `v23.0.0`, I managed to fix it by closing Sparrow and Bitcoin Core, deleting the sparrow folder it created with some wallet data, restarted Bitcoin Core and then restarted Sparrow... now it connected right away
